[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"

[[headers]]
  for = "/*"
  [headers.values]
  # Відкриваємо мережеві з’єднання для будь-яких bridge-ендпоінтів гаманців
  # (Tonkeeper, Tonhub, MyTonWallet, Okx, Trust, Bitget, інші — тепер не буде блокувань)
  Content-Security-Policy = '''
    default-src 'self';
    img-src 'self' data: https:;
    font-src 'self' data: https:;
    connect-src 'self' https: wss:;
    frame-src 'self' https:;
    media-src 'self' https:;
    script-src 'self' 'unsafe-inline' 'unsafe-eval' https:;
    style-src 'self' 'unsafe-inline' https:;
  '''
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Content-Type-Options = "nosniff"
