[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"

[[headers]]
  for = "/*"
  [headers.values]
  # Дозволяємо гаманцям підтягувати іконки та відкривати з’єднання з їхніми бриджами
  Content-Security-Policy = '''
    default-src 'self';
    img-src 'self' data: https:;
    connect-src 'self'
      https://connect.tonhubapi.com
      https://bridge.tonapi.io
      https://tonapi.io
      https://*.tonkeeper.com
      https://raw.githubusercontent.com;
    frame-src 'self' https:;
    media-src 'self' https:;
    script-src 'self' 'unsafe-inline' 'unsafe-eval' https:;
    style-src 'self' 'unsafe-inline' https:;
  '''
